/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Copyright: typeof import('./theme/components/Copyright.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    Progress: typeof import('./theme/components/Progress.vue')['default']
  }
}
